import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Fira_Sans, Fira_Code } from "next/font/google";
import { ThemeProvider } from "@/components/provider/ThemeProvider"; // Pastikan path import benar

const firaSans = Fira_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fira-sans",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata = {
  title: "ALMADEV",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${firaSans.variable} ${firaCode.variable} antialiased font-sans bg-background text-foreground`}
      >
        {/* PENTING: Gunakan attribute="class" agar kompatibel dengan Tailwind dark: modifier */}
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster position='top-center' />
        </ThemeProvider>
      </body>
    </html>
  );
}
